apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pric17vqk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pric17vqk-python 
  name: pric17vqk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pric17vqk-python 
